services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma_docker_starter_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    command: tail -f /dev/null # index.tsを作成するまで暫定対応
    # ports:
    #   - "3000:3000"

  db:
    image: postgres:16-alpine
    container_name: prisma_docker_starter_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: